name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-node-app:latest

    # Run the Docker container
    - name: Run the Docker container
      run: docker run -d -p 3000:3000 my-node-app
